language: go

go:
  - 1.9.x
  - 1.8.x
  - 1.7.x

script:
  - diff -u <(echo -n) <(gofmt -d .)
  - go vet -v ./...
  - go test -v ./...

notifications:
  email:
    on_success: change
    on_failure: always
